name: SuperTrailsPro
version: v2.1.0
main: me.saynt.supertrailspro.SuperTrails
author: [kvq]
api-version: '26.3'
loadbefore: [SuperTrails]
softdepend: [Citizens]
commands:
  trails:
    description: null
  supertrails:
    description: null
  trailsid:
    description: null